global_frame: map
robot_base_frame: base_footprint

obstacle_range: 2.5
raytrace_range: 3.0

inflation_radius: 0.30
footprint: [[-0.1,0.1],[0.1, 0.1],[0.1,-0.1],[-0.1,-0.1]]

observation_sources: rplidar 
rplidar: {sensor_frame: laser_link, data_type: LaserScan, topic: scan, marking: true, clearing: true}
