global_costmap:
  global_frame: map
  robot_base_frame: base_footprint

  inflation_radius: 0.2
  footprint: [[-0.08,0.08],[0.08, 0.08],[0.08,-0.08],[-0.08,-0.08]]
  
  observation_sources: rplidar 
  rplidar: {sensor_frame: laser_link, data_type: LaserScan, topic: scan, marking: true, clearing: true}

  update_frequency: 1.0
