local_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  
  inflation_radius: 0.15
  footprint: [[-0.08,0.08],[0.08, 0.08],[0.08,-0.08],[-0.08,-0.08]]
  
  observation_sources: rplidar 
  rplidar: {sensor_frame: laser_link, data_type: LaserScan, topic: scan, marking: true, clearing: true}

  update_frequency: 5.0
  publish_frequency: 2.0
  rolling_window: true

  width: 7.0
  height: 7.0
  resolution: 0.025

  plugins: 
  - name: static_map
    type: "costmap_2d::StaticLayer"
  - name: obstacles
    type: "costmap_2d::VoxelLayer"
  - name: inflation
    type: "costmap_2d::InflationLayer"
  
  obstacles:
    observation_sources: rplidar
    rplidar: {sensor_frame: laser_link, data_type: LaserScan, topic: scan, marking: true, clearing: true}

    max_obstacle_height: 0.4
    z_resolution: 0.05
    z_voxels: 10
    publish_voxel_map: true

  inflation:
    inflation_radius: 0.01
