local_costmap:
  update_frequency: 1.0
  publish_frequency: 1.0
  static_map: false
  rolling_window: true
  width: 5.0
  height: 5.0
  resolution: 0.05
  plugins: 
  - name: static_map
    type: "costmap_2d::StaticLayer"
  - name: obstacles
    type: "costmap_2d::VoxelLayer"
  - name: inflation
    type: "costmap_2d::InflationLayer"
  
  obstacles:
    observation_sources: rplidar
    rplidar: {sensor_frame: laser_link, data_type: LaserScan, topic: scan, marking: true, clearing: true}

    max_obstacle_height: 0.4
    z_resolution: 0.05
    z_voxels: 10
    publish_voxel_map: true

  inflation:
    inflation_radius: 0.01
